package main

import (
	"bufio"
	"context"
	"crypto/hmac"
	"io"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/core/protocol"
	ma "github.com/multiformats/go-multiaddr"

	"github.com/shurlinet/shurli/internal/auth"
	"github.com/shurlinet/shurli/internal/config"
	"github.com/shurlinet/shurli/internal/identity"
	"github.com/shurlinet/shurli/internal/invite"
	"github.com/shurlinet/shurli/internal/relay"
	"github.com/shurlinet/shurli/internal/validate"
	"github.com/shurlinet/shurli/pkg/p2pnet"
)

func runJoin(args []string) {
	// Reorder args: move flags before positional args.
	// Go's flag.Parse stops at the first non-flag argument, but users
	// naturally write "shurli join <code> --as laptop". Without reordering,
	// --as and laptop get joined into the invite code, corrupting it.
	args = reorderArgs(args, map[string]bool{"non-interactive": true})

	fs := flag.NewFlagSet("join", flag.ExitOnError)
	configFlag := fs.String("config", "", "path to config file")
	nameFlag := fs.String("as", "", "your node's name on the network (e.g., \"laptop\")")
	relayFlag := fs.String("relay", "", "relay address (IP:PORT or full multiaddr) - bootstraps config on fresh devices")
	userFlag := fs.Bool("user", false, "install config in ~/.config/shurli/ instead of /etc/shurli/")
	nonInteractive := fs.Bool("non-interactive", false, "machine-friendly output for scripting")
	fs.Parse(reorderFlags(fs, args))

	// In non-interactive mode, progress goes to stderr so stdout is clean.
	out := fmt.Printf
	outln := fmt.Println
	if *nonInteractive {
		out = func(format string, a ...any) (int, error) { return fmt.Fprintf(os.Stderr, format, a...) }
		outln = func(a ...any) (int, error) { return fmt.Fprintln(os.Stderr, a...) }
	}

	// Resolve invite code: CLI arg > SHURLI_INVITE_CODE env var > stdin (non-interactive only)
	var code string
	if fs.NArg() >= 1 {
		code = strings.Join(fs.Args(), "")
	} else if env := os.Getenv("SHURLI_INVITE_CODE"); env != "" {
		code = strings.TrimSpace(env)
	} else if *nonInteractive {
		// Read one line from stdin
		scanner := bufio.NewScanner(os.Stdin)
		scanner.Buffer(make([]byte, 4096), 4096)
		if scanner.Scan() {
			code = strings.TrimSpace(scanner.Text())
		}
	}

	if code == "" {
		fmt.Println("Usage: shurli join <invite-code> [--as \"laptop\"] [--non-interactive]")
		fmt.Println()
		fmt.Println("The invite code is generated by 'shurli invite' on the other machine.")
		fmt.Println()
		fmt.Println("In non-interactive mode, the code can also come from:")
		fmt.Println("  SHURLI_INVITE_CODE environment variable")
		fmt.Println("  stdin (one line)")
		osExit(1)
	}

	// Decode invite
	data, err := invite.Decode(code)
	if err != nil {
		fatal("Invalid invite code: %v", err)
	}

	runPairJoin(data, *nameFlag, *configFlag, *relayFlag, *userFlag, *nonInteractive, out, outln)
}

// runPairJoin handles invite codes with PAKE-secured relay pairing.
// The code contains only the token (no relay address). The joiner uses their configured relay.
func runPairJoin(data *invite.InviteData, nameFlag, configFlag, relayAddr string, userMode, nonInteractive bool,
	out func(string, ...any) (int, error), outln func(...any) (int, error)) {

	outln("=== Shurli join ===")
	outln()

	// Resolve config. v3 codes have no relay address, so use existing config.
	cfgFile, err := config.FindConfigFile(configFlag)
	if err != nil {
		if relayAddr == "" {
			fatal("No config found. Run 'shurli init' first, or use --relay to bootstrap:\n  shurli join <code> --relay <IP:PORT> --as <name>")
		}
		// Bootstrap: create identity + config from scratch using the provided relay.
		outln("No config found. Bootstrapping from --relay flag...")
		outln()
		cfgFile, err = bootstrapForJoin(relayAddr, userMode, os.Stdin, os.Stdout)
		if err != nil {
			fatal("Bootstrap failed: %v", err)
		}
	}
	cfg, err := config.LoadNodeConfig(cfgFile)
	if err != nil {
		fatal("Config error: %v", err)
	}
	configDir := filepath.Dir(cfgFile)
	config.ResolveConfigPaths(cfg, configDir)

	out("Using config: %s\n", cfgFile)

	if len(cfg.Relay.Addresses) == 0 {
		fatal("No relay addresses in config.\n  Add one with: shurli relay add <address>\n  Or run: shurli init")
	}

	// Resolve password for SHRL-encrypted identity key.
	pw, _ := resolvePassword(configDir)

	// Create P2P network.
	p2pNetwork, err := p2pnet.New(&p2pnet.Config{
		KeyFile:            cfg.Identity.KeyFile,
		KeyPassword:        pw,
		Config:             &config.Config{Network: cfg.Network},
		UserAgent:          "shurli/" + version,
		Namespace:          cfg.Discovery.Network,
		EnableRelay:        true,
		RelayAddrs:         cfg.Relay.Addresses,
		ForcePrivate:       cfg.Network.ForcePrivateReachability,
		EnableNATPortMap:   true,
		EnableHolePunching: true,
	})
	if err != nil {
		fatal("P2P network error: %v", err)
	}
	defer p2pNetwork.Close()

	h := p2pNetwork.Host()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	out("Your Peer ID: %s\n", h.ID())
	outln()

	// Connect to relay.
	outln("Connecting to relay...")
	relayInfos, err := p2pnet.ParseRelayAddrs(cfg.Relay.Addresses)
	if err != nil {
		fatal("Failed to parse relay addresses: %v", err)
	}
	for _, ai := range relayInfos {
		if err := h.Connect(ctx, ai); err != nil {
			fatal("Failed to connect to relay: %v", err)
		}
	}
	outln("Connected to relay.")

	// Open PAKE invite protocol stream to relay.
	outln("Authenticating with invite code...")
	relayPeerID := relayInfos[0].ID
	pairCtx := network.WithAllowLimitedConn(ctx, relay.InviteProtocol)
	s, err := h.NewStream(pairCtx, relayPeerID, protocol.ID(relay.InviteProtocol))
	if err != nil {
		fatal("Failed to open pairing stream: %v", err)
	}
	defer s.Close()

	// PAKE handshake: send [32] SHA-256(token) + [32] X25519 pubkey.
	tokenHash := sha256.Sum256(data.Token)
	session, err := invite.NewPAKESession()
	if err != nil {
		fatal("PAKE session error: %v", err)
	}

	var handshake [64]byte
	copy(handshake[:32], tokenHash[:])
	copy(handshake[32:], session.PublicKey())
	if _, err := s.Write(handshake[:]); err != nil {
		fatal("Failed to send handshake: %v", err)
	}

	// Read [1] status + [32] relay X25519 pubkey.
	var statusBuf [1]byte
	if _, err := s.Read(statusBuf[:]); err != nil {
		fatal("Failed to read relay response: %v", err)
	}
	if statusBuf[0] != relay.StatusOK {
		fatal("Invite code rejected by relay")
	}

	relayPub, err := invite.ReadPublicKey(s)
	if err != nil {
		fatal("Failed to read relay public key: %v", err)
	}

	// Complete PAKE with token as salt.
	// Channel binding: include relay's peer ID to prevent relay swap attacks.
	relayBinding := []byte(relayPeerID)
	if err := session.Complete(relayPub, data.Token, relayBinding); err != nil {
		fatal("PAKE key exchange failed: %v", err)
	}

	// Send encrypted name.
	if err := session.WriteEncrypted(s, []byte(nameFlag)); err != nil {
		fatal("Failed to send encrypted name: %v", err)
	}

	// Read encrypted response (PairingResponse JSON).
	respBytes, err := session.Decrypt(s)
	if err != nil {
		fatal("Authentication failed (wrong invite code?): %v", err)
	}

	var pairResp relay.PairingResponse
	if err := json.Unmarshal(respBytes, &pairResp); err != nil {
		fatal("Failed to parse relay response: %v", err)
	}

	outln()
	outln("=== Joined successfully! ===")
	outln()

	// Add discovered peers to authorized_keys and config names.
	authKeysPath := cfg.Security.AuthorizedKeysFile

	// Authorize relay and annotate with group ID.
	if pairResp.GroupID != "" {
		if err := auth.AddPeer(authKeysPath, relayPeerID.String(), "relay"); err != nil {
			if !strings.Contains(err.Error(), "already authorized") {
				log.Printf("Warning: failed to authorize relay: %v", err)
			}
		}
		auth.SetPeerAttr(authKeysPath, relayPeerID.String(), "group", pairResp.GroupID)

		// Compute and store own HMAC commitment proof.
		mac := hmac.New(sha256.New, data.Token)
		mac.Write([]byte(pairResp.GroupID))
		ownProof := mac.Sum(nil)
		auth.SetPeerAttr(authKeysPath, relayPeerID.String(), "hmac_proof", hex.EncodeToString(ownProof))
	}

	// Store macaroon if received.
	if pairResp.Macaroon != "" {
		macFile := filepath.Join(configDir, "macaroon.json")
		if err := os.WriteFile(macFile, []byte(pairResp.Macaroon), 0600); err != nil {
			log.Printf("Warning: could not save macaroon: %v", err)
		} else {
			out("Macaroon saved: %s\n", macFile)
		}
	}

	// Load existing names for conflict resolution.
	existingNames := make(map[string]bool)
	if cfg.Names != nil {
		for n := range cfg.Names {
			existingNames[n] = true
		}
	}

	for _, p := range pairResp.Peers {
		peerName := sanitizeYAMLName(p.Name)
		if peerName == "" {
			peerName = "peer-" + p.PeerID.String()[:8]
		}

		finalName := uniqueName(peerName, existingNames)
		if finalName != peerName {
			out("Name \"%s\" already in use. Registered as \"%s\".\n", peerName, finalName)
		}
		existingNames[finalName] = true

		if err := auth.AddPeer(authKeysPath, p.PeerID.String(), finalName); err != nil {
			if !strings.Contains(err.Error(), "already authorized") {
				log.Printf("Warning: failed to authorize peer: %v", err)
			}
		}
		if pairResp.GroupID != "" {
			auth.SetPeerAttr(authKeysPath, p.PeerID.String(), "group", pairResp.GroupID)
		}

		updateConfigNames(cfgFile, configDir, finalName, p.PeerID.String())

		emoji, numeric := p2pnet.ComputeFingerprint(h.ID(), p.PeerID)
		out("Peer \"%s\" authorized. [UNVERIFIED]\n", finalName)
		out("  Verification code: %s  (%s)\n", emoji, numeric)
		out("  Verify with: shurli verify %s\n", finalName)
		outln()
	}

	if len(pairResp.Peers) == 0 {
		outln("Authorized on relay. No other peers in this group yet.")
		outln()
	}

	out("Config: %s\n", cfgFile)
	out("Authorized keys: %s\n", authKeysPath)
	outln()

	// Auto-start daemon.
	outln("Starting daemon...")
	var daemonPID int
	if started := kickServiceDaemon(); !started {
		daemonCmd := exec.Command(os.Args[0], "daemon")
		daemonCmd.Stdout = nil
		daemonCmd.Stderr = nil
		daemonCmd.SysProcAttr = detachedProcAttr()
		if err := daemonCmd.Start(); err != nil {
			out("Could not auto-start daemon: %v\n", err)
			out("Start manually with: shurli daemon\n")
		} else {
			daemonPID = daemonCmd.Process.Pid
			out("Daemon started (PID %d). Logs: /tmp/shurli-daemon.log\n", daemonPID)
		}
	}

	// Offer systemd service installation (Linux only, interactive only).
	if !nonInteractive {
		reader := bufio.NewReader(os.Stdin)
		promptInstallService(reader, os.Stdout, daemonPID)
	}

	if !nonInteractive && len(pairResp.Peers) > 0 {
		outln()
		outln("Try:")
		out("  shurli ping %s\n", sanitizeYAMLName(pairResp.Peers[0].Name))
	}
}

// uniqueName appends a numeric suffix if name already exists in the set.
func uniqueName(name string, existing map[string]bool) string {
	if !existing[name] {
		return name
	}
	for i := 2; i <= 100; i++ {
		candidate := fmt.Sprintf("%s-%d", name, i)
		if !existing[candidate] {
			return candidate
		}
	}
	return fmt.Sprintf("%s-%d", name, time.Now().Unix())
}

// sanitizeYAMLName strips characters unsafe for use as a bare YAML key.
// Only allows alphanumeric, hyphen, underscore, and dot.
// Names are capped at 64 characters to prevent abuse from remote peers.
func sanitizeYAMLName(s string) string {
	const maxNameLen = 64
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' || r == '.' {
			b.WriteRune(r)
			if b.Len() >= maxNameLen {
				break
			}
		}
	}
	return b.String()
}

// addRelayToConfigFile adds a relay address to the config file's relay.addresses section.
// Handles both "addresses:" (empty list) and "addresses: []" formats.
func addRelayToConfigFile(cfgFile, relayAddr string) error {
	data, err := os.ReadFile(cfgFile)
	if err != nil {
		return err
	}

	lines := strings.Split(string(data), "\n")
	var result []string
	added := false
	entry := fmt.Sprintf("    - \"%s\"", relayAddr)

	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])

		// Handle "addresses: []" inline empty array.
		if !added && trimmed == "addresses: []" {
			idx := strings.Index(lines[i], "addresses:")
			result = append(result, lines[i][:idx]+"addresses:")
			result = append(result, entry)
			added = true
			for k := i + 1; k < len(lines); k++ {
				result = append(result, lines[k])
			}
			break
		}

		result = append(result, lines[i])

		// Handle "addresses:" multi-line format (empty or with entries).
		if !added && trimmed == "addresses:" {
			// Skip past any existing entries.
			for i+1 < len(lines) {
				next := strings.TrimSpace(lines[i+1])
				if strings.HasPrefix(next, "- ") {
					i++
					result = append(result, lines[i])
				} else {
					break
				}
			}
			result = append(result, entry)
			added = true
		}
	}

	if !added {
		return fmt.Errorf("could not find relay.addresses section")
	}

	return os.WriteFile(cfgFile, []byte(strings.Join(result, "\n")), 0600)
}

// updateConfigNames appends a name mapping to the config file.
// This does a simple text append to preserve formatting and comments.
func updateConfigNames(cfgFile, configDir, name, peerIDStr string) {
	// Sanitize name to prevent YAML injection  - the name comes from a remote peer
	name = sanitizeYAMLName(name)
	if name == "" {
		log.Printf("Warning: peer name was empty after sanitization, skipping names update")
		return
	}

	data, err := os.ReadFile(cfgFile)
	if err != nil {
		log.Printf("Warning: could not read config to update names: %v", err)
		return
	}

	content := string(data)

	// Skip if this exact name+peerID mapping already exists in the config.
	// This prevents duplicate entries when peer-notify re-delivers introductions.
	expectedEntry := fmt.Sprintf("%s: \"%s\"", name, peerIDStr)
	if strings.Contains(content, expectedEntry) {
		return
	}

	// Replace "names: {}" with a proper names block
	if strings.Contains(content, "names: {}") {
		replacement := fmt.Sprintf("names:\n  %s: \"%s\"", name, peerIDStr)
		content = strings.Replace(content, "names: {}", replacement, 1)
	} else if strings.Contains(content, "names:") {
		// Append under existing names section after the last entry.
		lines := strings.Split(content, "\n")
		var result []string
		added := false
		indent := "  " // default indentation
		namesIdx := -1
		lastEntryIdx := -1

		// Find the names: line and the last entry under it.
		for i, line := range lines {
			trimmed := strings.TrimSpace(line)
			if namesIdx < 0 && strings.HasPrefix(trimmed, "names:") && !strings.Contains(line, "{}") {
				namesIdx = i
				continue
			}
			if namesIdx >= 0 && !added {
				// Lines under names: that look like entries (key: "value"), skip comments.
				if !strings.HasPrefix(trimmed, "#") && (strings.Contains(trimmed, ": \"") || strings.Contains(trimmed, ": '")) {
					lastEntryIdx = i
					// Detect indentation from this entry.
					indent = line[:len(line)-len(strings.TrimLeft(line, " \t"))]
				} else if trimmed != "" && !strings.HasPrefix(trimmed, "#") {
					// Non-empty, non-comment line = end of names section.
					added = true
				}
			}
		}

		// Insert after the last entry (or after names: if no entries).
		insertAfter := lastEntryIdx
		if insertAfter < 0 {
			insertAfter = namesIdx
		}
		for i, line := range lines {
			result = append(result, line)
			if !added && i == insertAfter {
				result = append(result, fmt.Sprintf("%s%s: \"%s\"", indent, name, peerIDStr))
				added = true
			}
		}
		if !added {
			result = append(result, fmt.Sprintf("\nnames:\n  %s: \"%s\"", name, peerIDStr))
		}
		content = strings.Join(result, "\n")
	} else {
		// No names section at all
		content += fmt.Sprintf("\nnames:\n  %s: \"%s\"\n", name, peerIDStr)
	}

	if err := os.WriteFile(cfgFile, []byte(content), 0600); err != nil {
		log.Printf("Warning: could not update config names: %v", err)
	}
}

// sudoRun executes a command with sudo, inheriting stdin/stdout/stderr
// so the user can enter their password if needed.
func sudoRun(args ...string) error {
	cmd := exec.Command("sudo", args...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// bootstrapForJoin creates a fresh identity and config for a device that has never
// run "shurli init". This enables "shurli join <code> --relay <addr>" as a single
// command for new devices. Returns the path to the created config file.
func bootstrapForJoin(relayInput string, userMode bool, stdin io.Reader, stdout io.Writer) (string, error) {
	// Validate relay address: accept full multiaddr or IP:PORT.
	var relayAddr string
	if isFullMultiaddr(relayInput) {
		if _, err := ma.NewMultiaddr(relayInput); err != nil {
			return "", fmt.Errorf("invalid multiaddr: %w", err)
		}
		relayAddr = relayInput
	} else {
		// IP:PORT format - need peer ID interactively.
		ip, port, err := parseRelayHostPort(relayInput)
		if err != nil {
			return "", fmt.Errorf("invalid relay address: %w", err)
		}
		reader := bufio.NewReader(stdin)
		fmt.Fprintln(stdout, "Enter the relay server's Peer ID:")
		fmt.Fprint(stdout, "> ")
		peerIDStr, err := reader.ReadString('\n')
		if err != nil {
			return "", fmt.Errorf("failed to read input: %w", err)
		}
		peerIDStr = strings.TrimSpace(peerIDStr)
		if peerIDStr == "" {
			return "", fmt.Errorf("relay Peer ID is required")
		}
		if err := validatePeerID(peerIDStr); err != nil {
			return "", fmt.Errorf("invalid Peer ID: %w", err)
		}
		relayAddr = buildRelayMultiaddr(ip, port, peerIDStr)
	}

	// Determine config directory.
	var configDir string
	var dirErr error
	if userMode {
		configDir, dirErr = config.UserConfigDir()
	} else {
		configDir, dirErr = config.DefaultConfigDir()
	}
	if dirErr != nil {
		return "", fmt.Errorf("cannot determine config directory: %w", dirErr)
	}
	configFile := filepath.Join(configDir, "config.yaml")
	if _, err := os.Stat(configFile); err == nil {
		return "", fmt.Errorf("config already exists: %s", configFile)
	}

	fmt.Fprintf(stdout, "Config directory: %s\n", configDir)
	if err := os.MkdirAll(configDir, 0700); err != nil {
		// Needs sudo for /etc/shurli/
		if !userMode {
			fmt.Fprintln(stdout, "Creating system config directory (requires sudo)...")
			if sudoErr := sudoRun("mkdir", "-p", configDir); sudoErr != nil {
				return "", fmt.Errorf("failed to create directory: %w", sudoErr)
			}
			// chown to current user so we can write files without sudo
			user := os.Getenv("USER")
			if user == "" {
				user = "root"
			}
			if sudoErr := sudoRun("chown", "-R", user+":"+user, configDir); sudoErr != nil {
				return "", fmt.Errorf("failed to set ownership: %w", sudoErr)
			}
			if sudoErr := sudoRun("chmod", "700", configDir); sudoErr != nil {
				return "", fmt.Errorf("failed to set permissions: %w", sudoErr)
			}
		} else {
			return "", fmt.Errorf("failed to create directory: %w", err)
		}
	}

	// Identity: new or recover
	reader := bufio.NewReader(stdin)
	fmt.Fprintln(stdout)
	fmt.Fprintln(stdout, "Identity:")
	fmt.Fprintln(stdout, "  1. Create a new identity (default)")
	fmt.Fprintln(stdout, "  2. Recover from an existing seed phrase")
	fmt.Fprintln(stdout)
	fmt.Fprint(stdout, "Choice [1]: ")

	idChoice, idErr := reader.ReadString('\n')
	if idErr != nil {
		return "", fmt.Errorf("failed to read input: %w", idErr)
	}
	idChoice = strings.TrimSpace(idChoice)
	if idChoice == "" {
		idChoice = "1"
	}
	fmt.Fprintln(stdout)

	var privKey crypto.PrivKey
	switch idChoice {
	case "2":
		// Recover from existing seed phrase.
		fmt.Fprintln(stdout, "Enter your seed phrase to recover your identity.")
		fmt.Fprintln(stdout)
		mnemonic, mnErr := readSeedPhrase(stdout)
		if mnErr != nil {
			return "", fmt.Errorf("failed to read seed phrase: %w", mnErr)
		}
		if mnErr = identity.ValidateMnemonic(mnemonic); mnErr != nil {
			return "", fmt.Errorf("invalid seed phrase: %w", mnErr)
		}
		entropy, mnErr := identity.SeedFromMnemonic(mnemonic)
		if mnErr != nil {
			return "", fmt.Errorf("failed to decode seed: %w", mnErr)
		}
		var dErr error
		privKey, dErr = identity.DeriveIdentityKey(entropy)
		if dErr != nil {
			return "", fmt.Errorf("failed to derive identity key: %w", dErr)
		}
		recPeerID, _ := peer.IDFromPrivateKey(privKey)
		fmt.Fprintln(stdout, "Seed phrase accepted.")
		fmt.Fprintf(stdout, "Recovered Peer ID: %s\n\n", recPeerID)

	default:
		// Generate new BIP39 seed.
		fmt.Fprintln(stdout, "Generating identity...")
		fmt.Fprintln(stdout)

		mnemonic, entropy, genErr := identity.GenerateSeed()
		if genErr != nil {
			return "", fmt.Errorf("failed to generate seed: %w", genErr)
		}
		words := strings.Fields(mnemonic)

		fmt.Fprintln(stdout, "=== SEED PHRASE ===")
		fmt.Fprintln(stdout, "Write this down and store it securely. This is the ONLY way to")
		fmt.Fprintln(stdout, "recover your identity if you lose this device.")
		fmt.Fprintln(stdout)
		fmt.Fprint(stdout, formatSeedGrid(words))
		fmt.Fprintln(stdout)
		fmt.Fprintln(stdout, "===========================")
		fmt.Fprintln(stdout)

		if genErr = confirmSeedBackup(stdout, reader, words, false); genErr != nil {
			return "", fmt.Errorf("seed backup: %w", genErr)
		}
		fmt.Fprintln(stdout, "Seed backup confirmed.")
		fmt.Fprintln(stdout)

		var dErr error
		privKey, dErr = identity.DeriveIdentityKey(entropy)
		if dErr != nil {
			return "", fmt.Errorf("failed to derive identity key: %w", dErr)
		}
	}

	// Password setup.
	fmt.Fprintln(stdout, "Set a password to protect your identity:")
	fmt.Fprintf(stdout, "  Requirements: %d+ characters, at least 3 of: uppercase, lowercase, digit, symbol\n\n", validate.MinPasswordLen)

	var password string
	const maxAttempts = 3
	for attempt := 1; attempt <= maxAttempts; attempt++ {
		pw, pwErr := readPasswordConfirm("Password: ", "Confirm: ", stdout)
		if pwErr == nil {
			password = pw
			break
		}
		fmt.Fprintf(stdout, "  %v\n", pwErr)
		if attempt < maxAttempts {
			fmt.Fprintf(stdout, "  Try again (%d of %d)\n\n", attempt+1, maxAttempts)
		} else {
			return "", fmt.Errorf("password setup failed after %d attempts", maxAttempts)
		}
	}
	fmt.Fprintln(stdout)
	keyFile := filepath.Join(configDir, "identity.key")
	if err := identity.SaveIdentity(keyFile, privKey, password); err != nil {
		return "", fmt.Errorf("failed to save identity: %w", err)
	}

	// Create session token.
	if err := identity.CreateSession(configDir, password); err != nil {
		return "", fmt.Errorf("failed to create session: %w", err)
	}

	peerID, err := peer.IDFromPrivateKey(privKey)
	if err != nil {
		return "", fmt.Errorf("failed to derive peer ID: %w", err)
	}
	fmt.Fprintf(stdout, "Your Peer ID: %s\n", peerID)
	fmt.Fprintln(stdout)

	// Create authorized_keys.
	authKeysFile := filepath.Join(configDir, "authorized_keys")
	if _, err := os.Stat(authKeysFile); os.IsNotExist(err) {
		authContent := "# authorized_keys - Add peer IDs here (one per line)\n# Format: <peer_id> # optional comment\n"
		if err := os.WriteFile(authKeysFile, []byte(authContent), 0600); err != nil {
			return "", fmt.Errorf("failed to create authorized_keys: %w", err)
		}
	}

	// Write config.
	configContent := nodeConfigTemplate([]string{relayAddr}, "shurli join --relay", "")
	if err := os.WriteFile(configFile, []byte(configContent), 0600); err != nil {
		return "", fmt.Errorf("failed to write config: %w", err)
	}

	fmt.Fprintf(stdout, "Config written: %s\n", configFile)
	fmt.Fprintf(stdout, "Identity saved: %s\n", keyFile)
	fmt.Fprintln(stdout)

	// Install shell completions and man page.
	setupShellEnvironment(stdout)

	return configFile, nil
}
