package main

import (
	"fmt"
)

// nodeConfigTemplate returns the default config YAML for a new Shurli node.
// This is the single source of truth used by both "shurli init" and "shurli join".
// relayAddrs are the full multiaddrs of relay servers (one or more).
// generator identifies what created the config (e.g., "shurli init", "shurli join").
// network is the optional DHT namespace (empty = global network).
func nodeConfigTemplate(relayAddrs []string, generator, network string) string {
	networkLine := ""
	if network != "" {
		networkLine = fmt.Sprintf("  network: %q\n", network)
	}

	// Build YAML list of relay addresses
	var addrLines string
	for _, addr := range relayAddrs {
		addrLines += fmt.Sprintf("    - %q\n", addr)
	}

	return fmt.Sprintf(`# Shurli configuration
# Generated by: %s

version: 1

identity:
  key_file: "identity.key"

network:
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/0"
    - "/ip4/0.0.0.0/udp/0/quic-v1"
    - "/ip6/::/tcp/0"
    - "/ip6/::/udp/0/quic-v1"
  # Set to true on nodes behind CGNAT (required for shurli daemon)
  force_private_reachability: false

relay:
  addresses:
%s  reservation_interval: "2m"

discovery:
  rendezvous: "shurli-default-network"
%s  bootstrap_peers: []

security:
  authorized_keys_file: "authorized_keys"
  enable_connection_gating: true

protocols:
  ping_pong:
    enabled: true
    id: "/pingpong/1.0.0"

# Uncomment and configure services to expose (for shurli daemon):
# services:
#   ssh:
#     enabled: true
#     local_address: "localhost:22"
#   xrdp:
#     enabled: true
#     local_address: "localhost:3389"
#   web:
#     enabled: false
#     local_address: "localhost:80"

# Map friendly names to peer IDs:
names: {}
#  home: "PEER_ID_HERE"

# Peer relay (auto-enables when public IP detected):
# peer_relay:
#   enabled: "auto"  # "auto", "true", or "false"
#   resources:
#     max_reservations: 4
#     max_circuits: 16
#     circuit_duration: "10m"
#     circuit_data_limit: "128KB"

# Observability (disabled by default, opt-in):
# telemetry:
#   metrics:
#     enabled: true
#     listen_address: "127.0.0.1:9091"
#   audit:
#     enabled: true
`, generator, addrLines, networkLine)
}

// relayServerConfigTemplate returns the default relay server config YAML.
// This is the single source of truth used by "shurli relay setup".
// The sample file (configs/relay-server.sample.yaml) should be kept in sync
// with this template for users who prefer manual setup.
func relayServerConfigTemplate() string {
	return `# Relay Server Configuration
# Generated by: shurli relay setup

# Config schema version (do not change manually)
version: 1

identity:
  # Path to the key file for persistent peer identity
  # This file will be created automatically if it doesn't exist
  # IMPORTANT: Keep this file backed up - your peer ID depends on it
  key_file: "relay_node.key"

network:
  # Addresses to listen on
  # Default: port 7777 TCP (non-standard to avoid IPFS swarms)
  # Make sure this port is open in your firewall (ufw allow 7777/tcp)
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/7777"
    - "/ip6/::/tcp/7777"

    # Anti-censorship: WebSocket transport
    # Looks like regular HTTPS/WebSocket traffic to ISP deep packet inspection.
    # ISPs almost never block port 443 - it would break all web browsing.
    #
    # IMPORTANT: Port 443 is often used by web servers (nginx, Apache, Caddy).
    # Check first: ss -tlnp | grep :443
    # If port 443 is taken, pick any free port (setup.sh will detect
    # conflicts and suggest an available alternative automatically).
    #
    # Port 443 requires CAP_NET_BIND_SERVICE (setup.sh adds this).
    # Ports above 1024 (e.g., 8443, 9443) work without special capabilities.
    #
    # - "/ip4/0.0.0.0/tcp/443/ws"
    # - "/ip6/::/tcp/443/ws"

security:
  # Path to authorized_keys file
  # Only peers listed here can connect to this relay
  # Add one peer ID per line (home-node and client-node peer IDs)
  authorized_keys_file: "relay_authorized_keys"

  # Enable connection gating - STRONGLY RECOMMENDED for production
  # When true, only peers in authorized_keys can use this relay
  # When false, any peer on the internet can relay through your VPS
  enable_connection_gating: true

  # Data relay controls whether peers can forward data through this relay.
  # When false (default): only admin peers and peers with relay_data=true
  # attribute can establish data circuits. All peers can still use signaling
  # protocols (pairing, peer-notify, admin, etc.) since those are direct
  # streams, not relay circuits.
  # When true: all authorized peers can relay data (SSH, XRDP, etc.).
  # Per-peer exceptions: shurli relay authorize <peer-id> then
  #   set relay_data=true in authorized_keys for that peer.
  enable_data_relay: false

  # Vault protects root key material. Created automatically on first run.
  vault_file: "relay_vault.json"

# Relay resource limits (defaults shown - uncomment to customize)
# These control how much relay capacity each peer and session can consume.
# Tuned for private relays serving 2-10 peers with SSH/XRDP workloads.
# resources:
#   max_reservations: 128        # Total active relay slots
#   max_circuits: 16             # Open relay connections per peer
#   buffer_size: 2048            # Relay buffer size (bytes)
#   max_reservations_per_ip: 8   # Reservations per source IP
#   max_reservations_per_asn: 32 # Reservations per AS number
#   reservation_ttl: "1h"        # How long a reservation lasts
#   session_duration: "10m"      # Max duration per relayed session
#   session_data_limit: "64MB"   # Max data per session per direction

# Health check endpoint for monitoring (Prometheus, UptimeKuma, etc.)
# Disabled by default. Binds to localhost only - not exposed to the internet.
# To expose externally, use a reverse proxy or change listen_address.
# health:
#   enabled: true
#   listen_address: "127.0.0.1:9090"

# Observability (disabled by default, opt-in)
# When both health and metrics are enabled, /metrics shares the health endpoint.
# When only metrics is enabled, it starts its own HTTP server.
# telemetry:
#   metrics:
#     enabled: true
#     listen_address: "127.0.0.1:9091"  # Prometheus /metrics endpoint
#   audit:
#     enabled: true  # Structured JSON audit events to stderr
`
}
