package main

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
)

// nodeConfigTemplate returns the default config YAML for a new Shurli node.
// This is the single source of truth used by both "shurli init" and "shurli join".
// relayAddrs are the full multiaddrs of relay servers (one or more).
// generator identifies what created the config (e.g., "shurli init", "shurli join").
// network is the optional DHT namespace (empty = global network).
func nodeConfigTemplate(relayAddrs []string, generator, network string) string {
	networkLine := ""
	if network != "" {
		networkLine = fmt.Sprintf("  network: %q\n", network)
	}

	// Build YAML list of relay addresses
	var addrLines string
	for _, addr := range relayAddrs {
		addrLines += fmt.Sprintf("    - %q\n", addr)
	}

	return fmt.Sprintf(`# Shurli configuration
# Generated by: %s

version: 1

identity:
  key_file: "identity.key"

network:
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/0"
    - "/ip4/0.0.0.0/udp/0/quic-v1"
    - "/ip6/::/tcp/0"
    - "/ip6/::/udp/0/quic-v1"
  # Set to true on nodes behind CGNAT (required for shurli daemon)
  force_private_reachability: false

# Relay server addresses.
# Own relay (option 1 in init) = full capability: data relay, file transfer, proxy.
# Public seeds (option 2 in init) = discovery only, no data relay.
# Deploy your own: https://shurli.io/docs/relay-setup/
relay:
  addresses:
%s  reservation_interval: "2m"

discovery:
  rendezvous: "shurli-default-network"
%s  bootstrap_peers: []

security:
  authorized_keys_file: "authorized_keys"
  enable_connection_gating: true

protocols:
  ping_pong:
    enabled: true
    id: "/pingpong/1.0.0"

# Uncomment and configure services to expose (for shurli daemon):
# services:
#   ssh:
#     enabled: true
#     local_address: "localhost:22"
#   xrdp:
#     enabled: true
#     local_address: "localhost:3389"
#   web:
#     enabled: false
#     local_address: "localhost:80"

# Map friendly names to peer IDs:
names: {}
#  home: "PEER_ID_HERE"

# Peer relay (auto-enables when public IP detected):
# peer_relay:
#   enabled: "auto"  # "auto", "true", or "false"
#   resources:
#     max_reservations: 4
#     max_circuits: 16
#     circuit_duration: "10m"
#     circuit_data_limit: "128KB"

# Observability (disabled by default, opt-in):
# telemetry:
#   metrics:
#     enabled: true
#     listen_address: "127.0.0.1:9091"
#   audit:
#     enabled: true
`, generator, addrLines, networkLine)
}

// defaultReceiveDir returns a platform-appropriate default receive directory.
// macOS/Windows: ~/Downloads/shurli/  Linux: ~/shurli/received/
func defaultReceiveDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	if runtime.GOOS == "darwin" || runtime.GOOS == "windows" {
		return filepath.Join(home, "Downloads", "shurli")
	}
	return filepath.Join(home, "shurli", "received")
}

// createPluginDefaults creates the filetransfer plugin config directory and
// a default config.yaml so new nodes have a working receive_dir and sensible
// bandwidth_budget out of the box. Without this, every new node needs manual
// plugin config creation before file transfer works.
func createPluginDefaults(configDir string) {
	pluginDir := filepath.Join(configDir, "plugins", "shurli.io", "official", "filetransfer")
	if err := os.MkdirAll(pluginDir, 0700); err != nil {
		slog.Debug("init: could not create plugin config dir", "error", err)
		return
	}
	configPath := filepath.Join(pluginDir, "config.yaml")
	if _, err := os.Stat(configPath); err == nil {
		return // already exists
	}

	recvDir := defaultReceiveDir()
	if recvDir == "" {
		return
	}

	content := fmt.Sprintf(`# File transfer plugin configuration
# Generated automatically by shurli init/join

# Directory where received files are saved.
receive_dir: %q

# Who can send you files: "contacts" (authorized peers only), "ask", "open", "off"
receive_mode: "contacts"

# Per-peer bandwidth budget per hour. "unlimited", "500MB", "1GB", etc.
# LAN peers are always exempt regardless of this setting.
bandwidth_budget: "unlimited"
`, recvDir)

	if err := os.WriteFile(configPath, []byte(content), 0600); err != nil {
		slog.Debug("init: could not write plugin config", "error", err)
	}
}

// relayServerConfigTemplate returns the default relay server config YAML.
// This is the single source of truth used by "shurli relay setup".
// The sample file (configs/relay-server.sample.yaml) should be kept in sync
// with this template for users who prefer manual setup.
func relayServerConfigTemplate() string {
	return `# Relay Server Configuration
# Generated by: shurli relay setup

# Config schema version (do not change manually)
version: 1

identity:
  # Path to the key file for persistent peer identity
  # This file will be created automatically if it doesn't exist
  # IMPORTANT: Keep this file backed up - your peer ID depends on it
  key_file: "relay_node.key"

network:
  # Addresses to listen on
  # Default: port 7777 TCP (non-standard to avoid IPFS swarms)
  # Make sure this port is open in your firewall (ufw allow 7777/tcp)
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/7777"
    - "/ip6/::/tcp/7777"

    # Anti-censorship: WebSocket transport
    # Looks like regular HTTPS/WebSocket traffic to ISP deep packet inspection.
    # ISPs almost never block port 443 - it would break all web browsing.
    #
    # IMPORTANT: Port 443 is often used by web servers (nginx, Apache, Caddy).
    # Check first: ss -tlnp | grep :443
    # If port 443 is taken, pick any free port (setup.sh will detect
    # conflicts and suggest an available alternative automatically).
    #
    # Port 443 requires CAP_NET_BIND_SERVICE (setup.sh adds this).
    # Ports above 1024 (e.g., 8443, 9443) work without special capabilities.
    #
    # - "/ip4/0.0.0.0/tcp/443/ws"
    # - "/ip6/::/tcp/443/ws"

security:
  # Path to authorized_keys file
  # Only peers listed here can connect to this relay
  # Add one peer ID per line (home-node and client-node peer IDs)
  authorized_keys_file: "relay_authorized_keys"

  # Enable connection gating - STRONGLY RECOMMENDED for production
  # When true, only peers in authorized_keys can use this relay
  # When false, any peer on the internet can relay through your VPS
  enable_connection_gating: true

  # Data relay: whether authorized peers can relay data through this server.
  # Default: true (your relay, full capability for your peers).
  # When true: all authorized peers can relay data (file transfer, SSH, etc.).
  # When false: only admin peers and peers with active time-limited grants
  # can establish data circuits. All peers can still use signaling protocols.
  # For per-peer granular control, set to false and use:
  #   shurli relay grant <peer-id> --duration 1h
  enable_data_relay: true

  # Vault protects root key material. Created automatically on first run.
  vault_file: "relay_vault.json"

# Relay resource limits (defaults shown - uncomment to customize)
# These control how much relay capacity each peer and session can consume.
# Tuned for private relays serving 2-10 peers with SSH/XRDP workloads.
# resources:
#   max_reservations: 128        # Total active relay slots
#   max_circuits: 16             # Open relay connections per peer
#   buffer_size: 2048            # Relay buffer size (bytes)
#   max_reservations_per_ip: 8   # Reservations per source IP
#   max_reservations_per_asn: 32 # Reservations per AS number
#   reservation_ttl: "1h"        # How long a reservation lasts
#   session_duration: "10m"      # Max duration per relayed session
#   session_data_limit: "64MB"   # Max data per session per direction

# Health check endpoint for monitoring (Prometheus, UptimeKuma, etc.)
# Disabled by default. Binds to localhost only - not exposed to the internet.
# To expose externally, use a reverse proxy or change listen_address.
# health:
#   enabled: true
#   listen_address: "127.0.0.1:9090"

# Observability (disabled by default, opt-in)
# When both health and metrics are enabled, /metrics shares the health endpoint.
# When only metrics is enabled, it starts its own HTTP server.
# telemetry:
#   metrics:
#     enabled: true
#     listen_address: "127.0.0.1:9091"  # Prometheus /metrics endpoint
#   audit:
#     enabled: true  # Structured JSON audit events to stderr
`
}
