package main

import "fmt"

// nodeConfigTemplate returns the default config YAML for a new peer-up node.
// This is the single source of truth used by both "peerup init" and "peerup join".
// relayAddr is the full multiaddr of the relay server.
// generator identifies what created the config (e.g., "peerup init", "peerup join").
func nodeConfigTemplate(relayAddr, generator string) string {
	return fmt.Sprintf(`# peer-up configuration
# Generated by: %s

version: 1

identity:
  key_file: "identity.key"

network:
  listen_addresses:
    - "/ip4/0.0.0.0/tcp/0"
    - "/ip4/0.0.0.0/udp/0/quic-v1"
    - "/ip6/::/tcp/0"
    - "/ip6/::/udp/0/quic-v1"
  # Set to true on nodes behind CGNAT (required for peerup daemon)
  force_private_reachability: false

relay:
  addresses:
    - "%s"
  reservation_interval: "2m"

discovery:
  rendezvous: "peerup-default-network"
  bootstrap_peers: []

security:
  authorized_keys_file: "authorized_keys"
  enable_connection_gating: true

protocols:
  ping_pong:
    enabled: true
    id: "/pingpong/1.0.0"

# Uncomment and configure services to expose (for peerup daemon):
# services:
#   ssh:
#     enabled: true
#     local_address: "localhost:22"
#   xrdp:
#     enabled: true
#     local_address: "localhost:3389"
#   web:
#     enabled: false
#     local_address: "localhost:80"

# Map friendly names to peer IDs:
names: {}
#  home: "PEER_ID_HERE"

# Observability (disabled by default, opt-in):
# telemetry:
#   metrics:
#     enabled: true
#     listen_address: "127.0.0.1:9091"
#   audit:
#     enabled: true
`, generator, relayAddr)
}
